apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
      - name: broken
        image: invalidimage:doesnotexist
        ports:
        - containerPort: 80
